title =  "Creds Configuration"

[env]
    [env.local]
        user = ""
        token = ""
    [env.rest]
        user = ""
        token = ""

[credentials]
    [credentials.default]
        REDIS_USER = ""
        REDIS_DBNAME = ""
        REDIS_PORT = ""
        REDIS_PASSWORD = ""
        MONGO_USER = ""
        MONGO_DBNAME = ""
        MONGO_PORT = ""
        MONGO_PASSWORD = ""
        PSQL_USER = ""
        PSQL_DBNAME = ""
        PSQL_PORT = ""
        PSQL_PASSWORD = ""
    [credentials.retrieve]
        CLIENT_ID = ""
